language: objective-c
osx-image: xcode7.1
xcode_workspace: FlickerNumber.xcworkspace

script: xcodebuild -workspace FlickerNumber.xcworkspace -scheme FlickerNumber-Swift -destination 'platform=iOS Simulator,name=iPhone 6,OS=lastest' build ONLY_ACTIVE_ARCH=NO; xcodebuild -workspace FlickerNumber.xcworkspace -scheme FlickerNumber -destination 'platform=iOS Simulator,name=iPhone 6,OS=lastest' build ONLY_ACTIVE_ARCH=NO;
