language: objective-c
osx_image: xcode7.1

script: 
- xctool -workspace FlickerNumber.xcworkspace -scheme FlickerNumber -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO; 
- xctool -workspace FlickerNumber.xcworkspace -scheme FlickerNumber-Swift -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO;
