language: objective-c
osx-image: xcode7.1
xcode_workspace: FlickerNumber.xcworkspace

script:
- xctool -workspace FlickerNumber.xcworkspace -scheme FlickerNumber -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' build ONLY_ACTIVE_ARCH=NO
- xctool -workspace FlickerNumber.xcworkspace -scheme FlickerNumber-Swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' build ONLY_ACTIVE_ARCH=NO
